spring.datasource.url=jdbc:postgresql://localhost:5432/cosnima_db
spring.datasource.username=postgres
spring.datasource.password=pokemon2626
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=77bf6e9e9df6bbb55ee945ea42fc14f37bfaca9618c7363247f494f766f36366
jwt.expiration-ms=3600000
cloudinary.cloud-name=dkeg8l5uf
cloudinary.api-key=833694291668939
cloudinary.api-secret=rcIcyd_I5UO1KQKgyCTfgE6d69g
frontend.url=http://127.0.0.1:3000


spring.web.resources.add-mappings=false
